// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Writing = Collections['writings']['schema']['_output']
export declare const writings: Writing[]
